on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: Install esbuild dependencies
        run: sudo npm i -g esbuild
      - name: Install dependencies
        run: npm install
      - run: npm run test
      - uses: aws-actions/setup-sam@v2
      # - uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}
      - run: sam validate

      - run: sam build

      # - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name build-platform-PoC-CMS --s3-bucket ${{ secrets.S3_BUCKET_NAME }} --capabilities CAPABILITY_IAM --region ${{ secrets.AWS_REGION }}
